Repository osqledaren/osqledaren-frontend, pull requests merged in 2020-03, with the labels that each got.

#61 update category order in filter bar
  src/graphql/fragments.ts
  src/molecules/FilterBar.tsx
  src/utils/types.ts
Labels: bug

#63 Upgrade packages to new versions
  package.json
  yarn.lock
Labels: dependencies

#55 About page
  src/atoms/Link.tsx
  src/pages/about.tsx
Labels: feature
